name = "MonteCarloSummary"
uuid = "09b61566-bbdb-49ee-a687-6096cc4472a0"
authors = ["Andrew J. Radcliffe <andrewjradcliffe@gmail.com"]
version = "0.1.1"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
VectorizedReduction = "4ffe575c-65e5-43f4-bc05-e0b500dc3d2c"
VectorizedStatistics = "3b853605-1c98-4422-8364-4bd93ee0529e"

[compat]
LoopVectorization = "0.12.150"
VectorizedReduction = "0.1.8"
VectorizedStatistics = "0.5.2"
Statistics = "1.9.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
